### ISSUE TITLE
default RPC port

### ISSUE THREAD

**Issue by cipig** [crowdcoinChain/Crowdcoin#3]
Daemon uses the same default RPC port as DASH. Can this be changed to something else that is not already in use by other coin?

**Comment by crowdcoinChain** [comment]
hello, could you mention the file and the line?
we thought we have a different one setting it chainsparams.cpp.

Tk for your feedback

**Comment by cipig** [comment]
I searched for 9998 in the code and found it here
https://github.com/crowdcoinChain/Crowdcoin/blob/master/src/chainparamsbase.cpp#L35

**Comment by crowdcoinChain** [comment]
tk for the info, if you want you can do a pool request changing to a different port, it will be added to the new version

**Comment by cipig** [comment]
#9

**Comment by cipig** [comment]
PR merged, ticket closed
