### ISSUE TITLE
Error compiling on linux

### ISSUE THREAD

**Issue by adam1nowak1970** [crowdcoinChain/Crowdcoin#6]
Hi, to let you know I've got an error while building from sources:

rpcmining.cpp:466:10: error: ‘masternodeSync’ was not declared in this scope
     if (!masternodeSync.IsSynced())

Using configure with params:
./configure --disable-wallet --with-incompatible-bdb

**Comment by crowdcoinChain** [comment]
hi, why have you used that conf instead of the standard one ? or with without-gui param if you don't want to compile the gui version?

**Comment by adam1nowak1970** [comment]
configure without params throws:
‘class QDateTime’ has no member named ‘offsetFromUtc’

Probably QT version is different in my local env. Anyway I downloaded complied version from page.

Thanks
